services:
  mysql:
    image: mysql:8
    container_name: english-mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root12345
      MYSQL_DATABASE: testdb
      MYSQL_USER: english_user
      MYSQL_PASSWORD: 123456
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - english-net

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: english-backend
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    networks:
      - english-net
    env_file:
      - .env

volumes:
  mysql_data:

networks:
  english-net:
    driver: bridge
