version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: english-mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root12345
      MYSQL_DATABASE: testdb
      MYSQL_USER: english_user
      MYSQL_PASSWORD: 123456
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - english-net

volumes:
  mysql_data:

networks:
  english-net:
    driver: bridge
